# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from msilib.schema import ListBox
from pathlib import Path
import clipboard

import tkinter as tk
import tkinter.font as font
from turtle import update

import functions


class App(tk.Frame):
    def __init__(self, parent, *args, **kwargs):
        tk.Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent
        
        self.tasks = tk.Listbox(selectbackground='light slate blue', bg='Silver', font=('Helvetica', 32), height=10, width=40)
        self.tasks.place(x=500, y=252)
        self.update_text()

        myFont = font.Font(size=96)
        self.text = tk.StringVar()
        self.update_text()

        canvas = tk.Canvas(
            self,
            bg = "#FFFFFF",
            height = 1080,
            width = 1920,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            728.0,
            41.0,
            1192.0,
            163.0,
            fill="#f0f0f0",
            outline="")
        
        button_1 = tk.Button(
            borderwidth=0,
            highlightthickness=0,
            command=self.save_data,
            relief="flat",
            text="Save",
            font=myFont
        )
        button_1.place(
            x=300.0,
            y=809.0,
            width=400.0,
            height=150.0
        )
        button_2 = tk.Button(
            borderwidth=0,
            highlightthickness=0,
            command= self.load_data,
            relief="flat",
            text="Load",
            font=myFont
        )
        button_2.place(
            x=1220.0,
            y=809.0,
            width=400.0,
            height=150.0
        )
        button_3 = tk.Button(
            borderwidth=0,
            highlightthickness=0,
            command= self.delete_data,
            relief="flat",
            text="Delete",
            font=myFont
        )
        button_3.place(
            x=760.0,
            y=809.0,
            width=400.0,
            height=150.0
        )

        canvas.create_text(
            751.0,
            65.0,
            anchor="nw",
            text="MultiClipboard",
            fill="#000000",
            font=("Roboto", 64 * -1)
        )

    def save_data(self):
        USER_INP = tk.simpledialog.askstring(title="Input", prompt="Enter a key:")
        data = functions.load_clipboard_data()
        functions.save_clipboard_data(data, USER_INP)
        self.update_text()

    def load_data(self):
        try:
            chosen_data = self.tasks.get(self.tasks.curselection())
            chosen_data = chosen_data[chosen_data.find(':') + 2:]
            clipboard.copy(chosen_data)
        except:
            print('Nothing selected')

    def delete_data(self):
        try:
            data = functions.load_clipboard_data()
            chosen_data = self.tasks.get(self.tasks.curselection())
            chosen_data = chosen_data[:chosen_data.find(' ')]
            functions.delete_clipboard_data(data, chosen_data)
            self.update_text()
        except:
            print('Nothing selected')
            
    def update_text(self):
        self.tasks.delete(0, tk.END)
        data = functions.load_clipboard_data()
        for key, cp in data.items():
            self.tasks.insert(tk.END, key + ' : ' + cp)
